version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=${ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MEMCACHED_HOST=memcached

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  data-loader:
    build: ./data-generation
    environment:
      - API_URL=http://api:5000
      - ENV=${ENV}
    depends_on:
      - api
    restart: "no"

volumes:
  db_data:
