openapi: 3.0.3

info:
  title: Dome API
  version: 1.0.0
  description: API to intermediate communication between IoT sensors and database, as well serving as a back-end to the Dome Application.

servers:
  - url: http://localhost:5000

components:
  schemas:
    SensorMeasurementV1:
      $ref: 'sensor_measurement_v1.json'
    SensorExposureV1:
      $ref: 'sensor_exposure_v1.json'

paths:
  /v1/measurements:
    post:
      summary: Receives sensors measurements to be persisted in database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorMeasurementV1'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      summary: Retrieves a paginated list of sensor measurements
      parameters:
        - name: limit
          in: query
          required: false
          description: Number of records to return (default is 60)
          schema:
            type: integer
            default: 60
            minimum: 1
            example: 30
        - name: offset
          in: query
          description: "Offset to specify where to start the records from"
          schema:
            type: integer
            default: 0
            example: 0
      responses:
        '200':
          description: A list of sensor measurements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorMeasurementV1'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /v1/sensor-data:
    get:
      summary: Obter dados de sensores, focado na construção de gráficos
      parameters:
        - name: fields
          in: query
          description: "Campos a serem retornados. Exemplo: internalTemperature, luminosity. Se não especificado, todos os campos são retornados."
          required: false
          schema:
            type: string
            example: "internalTemperature, luminosity"
      responses:
        '200':
          description: Dados dos sensores
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorExposureV1'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error